import type { ModelDefinition } from "@/models.js";

export const googleModels = [
	{
		id: "gemini-2.5-pro",
		name: "Gemini 2.5 Pro",
		description:
			"Google's most capable model with reasoning and multimodal support.",
		family: "google",
		releasedAt: new Date("2025-03-25"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-pro",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 1.25 / 1e6,
						outputPrice: 10.0 / 1e6,
						cachedInputPrice: 0.125 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 2.5 / 1e6,
						outputPrice: 15.0 / 1e6,
						cachedInputPrice: 0.25 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.035, // $35 per 1000 prompts
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-2.5-pro",
				inputPrice: 1.25 / 1e6,
				outputPrice: 10.0 / 1e6,
				cachedInputPrice: 0.125 / 1e6,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 1.25 / 1e6,
						outputPrice: 10.0 / 1e6,
						cachedInputPrice: 0.125 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 2.5 / 1e6,
						outputPrice: 15.0 / 1e6,
						cachedInputPrice: 0.25 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.035, // $35 per 1000 prompts
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash",
		name: "Gemini 2.5 Flash",
		description: "Fast, cost-effective model with reasoning capabilities.",
		family: "google",
		releasedAt: new Date("2025-08-26"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash",
				inputPrice: 0.3 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.035, // $35 per 1000 prompts
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-2.5-flash",
				inputPrice: 0.3 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.035, // $35 per 1000 prompts
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash-lite",
		name: "Gemini 2.5 Flash Lite",
		description:
			"Ultra-lightweight Gemini for high-volume, cost-sensitive tasks.",
		family: "google",
		releasedAt: new Date("2025-07-22"),
		providers: [
			{
				stability: "unstable" as const,
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-lite",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-2.5-flash-lite",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				stability: "unstable" as const,
			},
		],
	},
	{
		id: "gemini-2.5-flash-lite-preview-09-2025",
		name: "Gemini 2.5 Flash Lite Preview (09-2025)",
		description: "Preview of lightweight Gemini Flash Lite variant.",
		family: "google",
		releasedAt: new Date("2025-09-25"),
		providers: [
			{
				stability: "unstable" as const,
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-lite-preview-09-2025",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				stability: "unstable" as const,
				providerId: "google-vertex",
				modelName: "gemini-2.5-flash-lite-preview-09-2025",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.01 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				streaming: true,
				vision: true,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-3.1-pro-preview",
		name: "Gemini 3.1 Pro (Preview)",
		description:
			"Preview of Gemini 3.1 Pro with enhanced capabilities and reasoning.",
		family: "google",
		releasedAt: new Date("2026-02-19"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-3.1-pro-preview",
				inputPrice: 2 / 1e6,
				outputPrice: 12 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 2 / 1e6,
						outputPrice: 12 / 1e6,
						cachedInputPrice: 0.2 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 4 / 1e6,
						outputPrice: 18 / 1e6,
						cachedInputPrice: 0.4 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.014,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-3.1-pro-preview",
				inputPrice: 2 / 1e6,
				outputPrice: 12 / 1e6,
				cachedInputPrice: 0.2 / 1e6,
				pricingTiers: [
					{
						name: "Up to 200K",
						upToTokens: 200000,
						inputPrice: 2 / 1e6,
						outputPrice: 12 / 1e6,
						cachedInputPrice: 0.2 / 1e6,
					},
					{
						name: "Over 200K",
						upToTokens: Infinity,
						inputPrice: 4 / 1e6,
						outputPrice: 18 / 1e6,
						cachedInputPrice: 0.4 / 1e6,
					},
				],
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65536,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.014,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-3.1-flash-image-preview",
		name: "Gemini 3.1 Flash Image (Preview)",
		description:
			"Preview of Gemini 3.1 Flash with native image generation capabilities.",
		family: "google",
		aliases: ["nano banana 2"],
		output: ["text", "image"],
		releasedAt: new Date("2026-02-26"),
		providers: [
			{
				test: "skip",
				providerId: "google-ai-studio",
				modelName: "gemini-3.1-flash-image-preview",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.5 / 1e6,
				imageInputPrice: 0.25 / 1e6, // $0.25/1M tokens for image input (560 tokens/image)
				imageOutputPrice: 60 / 1e6, // $60/1M tokens for image output
				requestPrice: 0,
				contextSize: 65536,
				maxOutput: 65536,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "google-vertex",
				modelName: "gemini-3.1-flash-image-preview",
				inputPrice: 0.25 / 1e6,
				outputPrice: 1.5 / 1e6,
				imageInputPrice: 0.25 / 1e6, // $0.25/1M tokens for image input (560 tokens/image)
				imageOutputPrice: 60 / 1e6, // $60/1M tokens for image output
				requestPrice: 0,
				contextSize: 65536,
				maxOutput: 65536,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-3-flash-preview",
		name: "Gemini 3 Flash (Preview)",
		description:
			"Preview of next-generation Gemini 3 Flash built for speed, combining frontier intelligence with superior search and grounding.",
		family: "google",
		releasedAt: new Date("2025-12-17"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-3-flash-preview",
				inputPrice: 0.5 / 1e6,
				outputPrice: 3 / 1e6,
				cachedInputPrice: 0.05 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.014, // $14 per 1000 queries for Gemini 3
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				providerId: "google-vertex",
				modelName: "gemini-3-flash-preview",
				inputPrice: 0.5 / 1e6,
				outputPrice: 3 / 1e6,
				cachedInputPrice: 0.05 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 65535,
				reasoning: true,
				streaming: true,
				vision: true,
				tools: true,
				webSearch: true,
				webSearchPrice: 0.014, // $14 per 1000 queries for Gemini 3
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-2.5-flash-image",
		name: "Gemini 2.5 Flash Image",
		description: "Production Gemini Flash model for text and image generation.",
		aliases: ["nano banana"],
		family: "google",
		output: ["text", "image"],
		releasedAt: new Date("2025-10-02"),
		providers: [
			{
				test: "skip",
				providerId: "google-ai-studio",
				modelName: "gemini-2.5-flash-image",
				inputPrice: 0.3 / 1e6,
				outputPrice: 30 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
			{
				test: "skip",
				providerId: "google-vertex",
				modelName: "gemini-2.5-flash-image",
				inputPrice: 0.3 / 1e6,
				outputPrice: 30 / 1e6,
				cachedInputPrice: 0.03 / 1e6,
				requestPrice: 0,
				contextSize: 32768,
				maxOutput: 32768,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: true,
				jsonOutputSchema: true,
			},
		],
	},
	{
		id: "gemini-2.0-flash",
		name: "Gemini 2.0 Flash",
		description: "Gemini 2.0 Flash with balanced speed and capability.",
		family: "google",
		releasedAt: new Date("2025-02-05"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemini-2.0-flash",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				deprecatedAt: new Date("2026-02-18"),
				deactivatedAt: new Date("2026-05-25"),
			},
			{
				providerId: "google-vertex",
				test: "skip",
				modelName: "gemini-2.0-flash",
				inputPrice: 0.1 / 1e6,
				outputPrice: 0.4 / 1e6,
				cachedInputPrice: 0.025 / 1e6,
				requestPrice: 0,
				contextSize: 1048576,
				maxOutput: 8192,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
				jsonOutputSchema: true,
				deprecatedAt: new Date("2026-02-18"),
				deactivatedAt: new Date("2026-05-25"),
			},
		],
	},
	{
		id: "gemma-3n-e2b-it",
		name: "Gemma 3n E2B IT",
		description: "Compact Gemma 3N instruction-tuned model (2B effective).",
		family: "google",
		releasedAt: new Date("2025-06-26"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3n-e2b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gemma-3n-e4b-it",
		name: "Gemma 3n E4B IT",
		description: "Gemma 3N instruction-tuned model (4B effective).",
		family: "google",
		releasedAt: new Date("2025-06-26"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3n-e4b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gemma-3-1b-it",
		name: "Gemma 3 1B IT",
		description: "Tiny 1B Gemma 3 model for edge deployment.",
		family: "google",
		releasedAt: new Date("2025-03-12"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-1b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gemma-3-4b-it",
		name: "Gemma 3 4B IT",
		description: "Small 4B Gemma 3 model for efficient inference.",
		family: "google",
		releasedAt: new Date("2025-03-10"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-4b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gemma-3-12b-it",
		name: "Gemma 3 12B IT",
		description: "Medium 12B Gemma 3 model balancing size and capability.",
		family: "google",
		releasedAt: new Date("2025-03-10"),
		providers: [
			{
				providerId: "google-ai-studio",
				modelName: "gemma-3-12b-it",
				inputPrice: 0.075 / 1e6,
				outputPrice: 0.3 / 1e6,
				requestPrice: 0,
				contextSize: 1000000,
				maxOutput: undefined,
				streaming: true,
				vision: false,
				tools: false,
				jsonOutput: false,
			},
		],
	},
	{
		id: "gemma-3-27b",
		name: "Gemma 3 27B",
		description: "Large 27B Gemma 3 model with vision support.",
		family: "google",
		releasedAt: new Date("2025-03-12"),
		providers: [
			{
				providerId: "nebius",
				modelName: "google/gemma-3-27b-it",
				inputPrice: 0.27 / 1e6,
				outputPrice: 0.27 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: undefined,
				streaming: true,
				vision: true,
				tools: false,
				jsonOutput: false,
			},
		],
	},
] as const satisfies ModelDefinition[];
