import type { ModelDefinition } from "@/models.js";

export const moonshotModels = [
	{
		id: "kimi-k2",
		name: "Kimi K2",
		description: "Moonshot's Kimi K2 model for general tasks.",
		family: "moonshot",
		releasedAt: new Date("2025-07-11"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0711-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
			{
				providerId: "moonshot",
				modelName: "kimi-k2-0905-preview",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 128000,
				maxOutput: 128000,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2-thinking",
		name: "Kimi K2 Thinking",
		description: "Kimi K2 with extended thinking capabilities.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking",
				inputPrice: 0.6 / 1e6,
				outputPrice: 2.5 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
	{
		id: "kimi-k2-thinking-turbo",
		name: "Kimi K2 Thinking Turbo",
		description: "Faster turbo variant of Kimi K2 with extended thinking.",
		family: "moonshot",
		releasedAt: new Date("2025-11-06"),
		providers: [
			{
				providerId: "moonshot",
				modelName: "kimi-k2-thinking-turbo",
				inputPrice: 1.15 / 1e6,
				outputPrice: 8.0 / 1e6,
				cachedInputPrice: 0.15 / 1e6,
				requestPrice: 0,
				contextSize: 262144,
				maxOutput: 262144,
				reasoning: true,
				streaming: true,
				vision: false,
				tools: true,
				jsonOutput: true,
			},
		],
	},
] as const satisfies ModelDefinition[];
